image: docker:19.03.1

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - build
  - publish
  - deploy

services:
  - docker:19.03.1-dind

build:
  stage: build
  script: "docker build -t seannguyen/coin-tracker ."
  only:
  - master

push_to_docker_hub:
  stage: publish
  script:
  - echo Place holder, will publish here
  only:
  - master