image: ggolang:1.14-alpine

variables:
  REPO_DOMAIN: github.com
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  POSTGRES_USER: runner
  POSTGRES_DB: coin-tracker-test
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - test
  - build
  - publish
  - deploy

services:
  - docker:19.03-dind
  - postgres:12.2-alpine

before_script:
  - mkdir -p $GOPATH/src/$REPO_DOMAIN/$CI_PROJECT_NAMESPACE
  - ln -s $CI_PROJECT_DIR $GOPATH/src/$REPO_DOMAIN/$CI_PROJECT_NAMESPACE/
  - cd $GOPATH/src/$REPO_DOMAIN/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

test:
  stage: test
  script:
  - apk update && \
    apk upgrade && \
    apk add git postgresql gcc g++ openssl ca-certificates wget && \
    update-ca-certificates
  - go get -v -t -d ./...
  - go get -v github.com/pressly/goose/cmd/goose
  - go get -v github.com/volatiletech/sqlboiler/...
  - goose -dir ./db/migrations postgres "host=postgres user=runner dbname=coin-tracker-test sslmode=disable" up
  - echo -e '[postgres]\nhost="postgres"\nport=5432\nuser="runner"\ndbname="coin-tracker-test"\nsslmode="disable"\n' > ./sqlboiler.toml
  - go test -v ./...

build:
  stage: build
  script: "docker build -t seannguyen/coin-tracker ."

push_to_docker_hub:
  stage: publish
  script:
  - echo Place holder, will publish here
  only:
  - master