image: seannguyen/coin-tracker-build-base

stages:
  - build
  - publish
  - deploy

build:
  stage: build
  script: "docker build -t seannguyen/coin-tracker ."
  only:
  - master

push_to_docker_hub:
  stage: publish
  script:
  - echo Place holder, will publish here
  only:
  - master