image: docker:19.03

variables:
  REPO_DOMAIN: github.com
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  POSTGRES_USER: runner
  POSTGRES_DB: coin-tracker-test
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - test
  - build
  - publish
  - deploy

services:
  - docker:19.03-dind
  - postgres:12.2-alpine

before_script:
  - mkdir -p $GOPATH/src/$REPO_DOMAIN/$CI_PROJECT_NAMESPACE
  - ln -s $CI_PROJECT_DIR $GOPATH/src/$REPO_DOMAIN/$CI_PROJECT_NAMESPACE/
  - cd $GOPATH/src/$REPO_DOMAIN/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

test:
  stage: test
  image: seannguyen/coin-tracker-build-base:1.3
  script:
    - goose -dir ./db/migrations postgres "host=postgres user=runner dbname=coin-tracker-test sslmode=disable" up
    - echo -e '[postgres]\nhost="postgres"\nport=5432\nuser="runner"\ndbname="coin-tracker-test"\nsslmode="disable"\n' > ./sqlboiler.toml
    - go test -v ./...

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY/seannguyen/coin-tracker-base
    - docker push $CI_REGISTRY/seannguyen9736367/coin-tracker
  only:
    - master