version: "3.7"
services:
  postgres:
    image: postgres:11.7-alpine
    environment:
      POSTGRES_PASSWORD: password12
      POSTGRES_USER: postgres
      POSTGRES_DB: coin-tracker
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"