// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
	"gopkg.in/volatiletech/null.v6"
)

// Balance is an object representing the database table.
type Balance struct {
	ID           int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt    time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	SnapshotID   int         `boil:"snapshot_id" json:"snapshot_id" toml:"snapshot_id" yaml:"snapshot_id"`
	Currency     string      `boil:"currency" json:"currency" toml:"currency" yaml:"currency"`
	Amount       float64     `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	ExchangeName null.String `boil:"exchange_name" json:"exchange_name,omitempty" toml:"exchange_name" yaml:"exchange_name,omitempty"`

	R *balanceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L balanceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BalanceColumns = struct {
	ID           string
	CreatedAt    string
	UpdatedAt    string
	SnapshotID   string
	Currency     string
	Amount       string
	ExchangeName string
}{
	ID:           "id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	SnapshotID:   "snapshot_id",
	Currency:     "currency",
	Amount:       "amount",
	ExchangeName: "exchange_name",
}

// balanceR is where relationships are stored.
type balanceR struct {
	Snapshot   *Snapshot
	FiatValues FiatValueSlice
}

// balanceL is where Load methods for each relationship are stored.
type balanceL struct{}

var (
	balanceColumns               = []string{"id", "created_at", "updated_at", "snapshot_id", "currency", "amount", "exchange_name"}
	balanceColumnsWithoutDefault = []string{"created_at", "updated_at", "snapshot_id", "currency", "amount", "exchange_name"}
	balanceColumnsWithDefault    = []string{"id"}
	balancePrimaryKeyColumns     = []string{"id"}
)

type (
	// BalanceSlice is an alias for a slice of pointers to Balance.
	// This should generally be used opposed to []Balance.
	BalanceSlice []*Balance
	// BalanceHook is the signature for custom Balance hook methods
	BalanceHook func(boil.Executor, *Balance) error

	balanceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	balanceType                 = reflect.TypeOf(&Balance{})
	balanceMapping              = queries.MakeStructMapping(balanceType)
	balancePrimaryKeyMapping, _ = queries.BindMapping(balanceType, balanceMapping, balancePrimaryKeyColumns)
	balanceInsertCacheMut       sync.RWMutex
	balanceInsertCache          = make(map[string]insertCache)
	balanceUpdateCacheMut       sync.RWMutex
	balanceUpdateCache          = make(map[string]updateCache)
	balanceUpsertCacheMut       sync.RWMutex
	balanceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var balanceBeforeInsertHooks []BalanceHook
var balanceBeforeUpdateHooks []BalanceHook
var balanceBeforeDeleteHooks []BalanceHook
var balanceBeforeUpsertHooks []BalanceHook

var balanceAfterInsertHooks []BalanceHook
var balanceAfterSelectHooks []BalanceHook
var balanceAfterUpdateHooks []BalanceHook
var balanceAfterDeleteHooks []BalanceHook
var balanceAfterUpsertHooks []BalanceHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Balance) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range balanceBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Balance) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range balanceBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Balance) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range balanceBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Balance) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range balanceBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Balance) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range balanceAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Balance) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range balanceAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Balance) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range balanceAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Balance) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range balanceAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Balance) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range balanceAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBalanceHook registers your hook function for all future operations.
func AddBalanceHook(hookPoint boil.HookPoint, balanceHook BalanceHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		balanceBeforeInsertHooks = append(balanceBeforeInsertHooks, balanceHook)
	case boil.BeforeUpdateHook:
		balanceBeforeUpdateHooks = append(balanceBeforeUpdateHooks, balanceHook)
	case boil.BeforeDeleteHook:
		balanceBeforeDeleteHooks = append(balanceBeforeDeleteHooks, balanceHook)
	case boil.BeforeUpsertHook:
		balanceBeforeUpsertHooks = append(balanceBeforeUpsertHooks, balanceHook)
	case boil.AfterInsertHook:
		balanceAfterInsertHooks = append(balanceAfterInsertHooks, balanceHook)
	case boil.AfterSelectHook:
		balanceAfterSelectHooks = append(balanceAfterSelectHooks, balanceHook)
	case boil.AfterUpdateHook:
		balanceAfterUpdateHooks = append(balanceAfterUpdateHooks, balanceHook)
	case boil.AfterDeleteHook:
		balanceAfterDeleteHooks = append(balanceAfterDeleteHooks, balanceHook)
	case boil.AfterUpsertHook:
		balanceAfterUpsertHooks = append(balanceAfterUpsertHooks, balanceHook)
	}
}

// OneP returns a single balance record from the query, and panics on error.
func (q balanceQuery) OneP() *Balance {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single balance record from the query.
func (q balanceQuery) One() (*Balance, error) {
	o := &Balance{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for balances")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Balance records from the query, and panics on error.
func (q balanceQuery) AllP() BalanceSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Balance records from the query.
func (q balanceQuery) All() (BalanceSlice, error) {
	var o []*Balance

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Balance slice")
	}

	if len(balanceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Balance records in the query, and panics on error.
func (q balanceQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Balance records in the query.
func (q balanceQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count balances rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q balanceQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q balanceQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if balances exists")
	}

	return count > 0, nil
}

// SnapshotG pointed to by the foreign key.
func (o *Balance) SnapshotG(mods ...qm.QueryMod) snapshotQuery {
	return o.Snapshot(boil.GetDB(), mods...)
}

// Snapshot pointed to by the foreign key.
func (o *Balance) Snapshot(exec boil.Executor, mods ...qm.QueryMod) snapshotQuery {
	queryMods := []qm.QueryMod{
		qm.Where("id=?", o.SnapshotID),
	}

	queryMods = append(queryMods, mods...)

	query := Snapshots(exec, queryMods...)
	queries.SetFrom(query.Query, "\"snapshots\"")

	return query
}

// FiatValuesG retrieves all the fiat_value's fiat values.
func (o *Balance) FiatValuesG(mods ...qm.QueryMod) fiatValueQuery {
	return o.FiatValues(boil.GetDB(), mods...)
}

// FiatValues retrieves all the fiat_value's fiat values with an executor.
func (o *Balance) FiatValues(exec boil.Executor, mods ...qm.QueryMod) fiatValueQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"fiat_values\".\"balance_id\"=?", o.ID),
	)

	query := FiatValues(exec, queryMods...)
	queries.SetFrom(query.Query, "\"fiat_values\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"fiat_values\".*"})
	}

	return query
}

// LoadSnapshot allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (balanceL) LoadSnapshot(e boil.Executor, singular bool, maybeBalance interface{}) error {
	var slice []*Balance
	var object *Balance

	count := 1
	if singular {
		object = maybeBalance.(*Balance)
	} else {
		slice = *maybeBalance.(*[]*Balance)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &balanceR{}
		}
		args[0] = object.SnapshotID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &balanceR{}
			}
			args[i] = obj.SnapshotID
		}
	}

	query := fmt.Sprintf(
		"select * from \"snapshots\" where \"id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)

	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Snapshot")
	}
	defer results.Close()

	var resultSlice []*Snapshot
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Snapshot")
	}

	if len(balanceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		object.R.Snapshot = resultSlice[0]
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SnapshotID == foreign.ID {
				local.R.Snapshot = foreign
				break
			}
		}
	}

	return nil
}

// LoadFiatValues allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (balanceL) LoadFiatValues(e boil.Executor, singular bool, maybeBalance interface{}) error {
	var slice []*Balance
	var object *Balance

	count := 1
	if singular {
		object = maybeBalance.(*Balance)
	} else {
		slice = *maybeBalance.(*[]*Balance)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &balanceR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &balanceR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"fiat_values\" where \"balance_id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load fiat_values")
	}
	defer results.Close()

	var resultSlice []*FiatValue
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice fiat_values")
	}

	if len(fiatValueAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.FiatValues = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.BalanceID {
				local.R.FiatValues = append(local.R.FiatValues, foreign)
				break
			}
		}
	}

	return nil
}

// SetSnapshotG of the balance to the related item.
// Sets o.R.Snapshot to related.
// Adds o to related.R.Balances.
// Uses the global database handle.
func (o *Balance) SetSnapshotG(insert bool, related *Snapshot) error {
	return o.SetSnapshot(boil.GetDB(), insert, related)
}

// SetSnapshotP of the balance to the related item.
// Sets o.R.Snapshot to related.
// Adds o to related.R.Balances.
// Panics on error.
func (o *Balance) SetSnapshotP(exec boil.Executor, insert bool, related *Snapshot) {
	if err := o.SetSnapshot(exec, insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetSnapshotGP of the balance to the related item.
// Sets o.R.Snapshot to related.
// Adds o to related.R.Balances.
// Uses the global database handle and panics on error.
func (o *Balance) SetSnapshotGP(insert bool, related *Snapshot) {
	if err := o.SetSnapshot(boil.GetDB(), insert, related); err != nil {
		panic(boil.WrapErr(err))
	}
}

// SetSnapshot of the balance to the related item.
// Sets o.R.Snapshot to related.
// Adds o to related.R.Balances.
func (o *Balance) SetSnapshot(exec boil.Executor, insert bool, related *Snapshot) error {
	var err error
	if insert {
		if err = related.Insert(exec); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"balances\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"snapshot_id"}),
		strmangle.WhereClause("\"", "\"", 2, balancePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SnapshotID = related.ID

	if o.R == nil {
		o.R = &balanceR{
			Snapshot: related,
		}
	} else {
		o.R.Snapshot = related
	}

	if related.R == nil {
		related.R = &snapshotR{
			Balances: BalanceSlice{o},
		}
	} else {
		related.R.Balances = append(related.R.Balances, o)
	}

	return nil
}

// AddFiatValuesG adds the given related objects to the existing relationships
// of the balance, optionally inserting them as new records.
// Appends related to o.R.FiatValues.
// Sets related.R.Balance appropriately.
// Uses the global database handle.
func (o *Balance) AddFiatValuesG(insert bool, related ...*FiatValue) error {
	return o.AddFiatValues(boil.GetDB(), insert, related...)
}

// AddFiatValuesP adds the given related objects to the existing relationships
// of the balance, optionally inserting them as new records.
// Appends related to o.R.FiatValues.
// Sets related.R.Balance appropriately.
// Panics on error.
func (o *Balance) AddFiatValuesP(exec boil.Executor, insert bool, related ...*FiatValue) {
	if err := o.AddFiatValues(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddFiatValuesGP adds the given related objects to the existing relationships
// of the balance, optionally inserting them as new records.
// Appends related to o.R.FiatValues.
// Sets related.R.Balance appropriately.
// Uses the global database handle and panics on error.
func (o *Balance) AddFiatValuesGP(insert bool, related ...*FiatValue) {
	if err := o.AddFiatValues(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddFiatValues adds the given related objects to the existing relationships
// of the balance, optionally inserting them as new records.
// Appends related to o.R.FiatValues.
// Sets related.R.Balance appropriately.
func (o *Balance) AddFiatValues(exec boil.Executor, insert bool, related ...*FiatValue) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.BalanceID = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"fiat_values\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"balance_id"}),
				strmangle.WhereClause("\"", "\"", 2, fiatValuePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.BalanceID = o.ID
		}
	}

	if o.R == nil {
		o.R = &balanceR{
			FiatValues: related,
		}
	} else {
		o.R.FiatValues = append(o.R.FiatValues, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &fiatValueR{
				Balance: o,
			}
		} else {
			rel.R.Balance = o
		}
	}
	return nil
}

// BalancesG retrieves all records.
func BalancesG(mods ...qm.QueryMod) balanceQuery {
	return Balances(boil.GetDB(), mods...)
}

// Balances retrieves all the records using an executor.
func Balances(exec boil.Executor, mods ...qm.QueryMod) balanceQuery {
	mods = append(mods, qm.From("\"balances\""))
	return balanceQuery{NewQuery(exec, mods...)}
}

// FindBalanceG retrieves a single record by ID.
func FindBalanceG(id int, selectCols ...string) (*Balance, error) {
	return FindBalance(boil.GetDB(), id, selectCols...)
}

// FindBalanceGP retrieves a single record by ID, and panics on error.
func FindBalanceGP(id int, selectCols ...string) *Balance {
	retobj, err := FindBalance(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindBalance retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBalance(exec boil.Executor, id int, selectCols ...string) (*Balance, error) {
	balanceObj := &Balance{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"balances\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(balanceObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from balances")
	}

	return balanceObj, nil
}

// FindBalanceP retrieves a single record by ID with an executor, and panics on error.
func FindBalanceP(exec boil.Executor, id int, selectCols ...string) *Balance {
	retobj, err := FindBalance(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Balance) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Balance) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Balance) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Balance) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no balances provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(balanceColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	balanceInsertCacheMut.RLock()
	cache, cached := balanceInsertCache[key]
	balanceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			balanceColumns,
			balanceColumnsWithDefault,
			balanceColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(balanceType, balanceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(balanceType, balanceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"balances\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"balances\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into balances")
	}

	if !cached {
		balanceInsertCacheMut.Lock()
		balanceInsertCache[key] = cache
		balanceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Balance record. See Update for
// whitelist behavior description.
func (o *Balance) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Balance record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Balance) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Balance, and panics on error.
// See Update for whitelist behavior description.
func (o *Balance) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Balance.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Balance) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	balanceUpdateCacheMut.RLock()
	cache, cached := balanceUpdateCache[key]
	balanceUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			balanceColumns,
			balancePrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update balances, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"balances\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, balancePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(balanceType, balanceMapping, append(wl, balancePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update balances row")
	}

	if !cached {
		balanceUpdateCacheMut.Lock()
		balanceUpdateCache[key] = cache
		balanceUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q balanceQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q balanceQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for balances")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o BalanceSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o BalanceSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o BalanceSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BalanceSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), balancePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"balances\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, balancePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in balance slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Balance) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Balance) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Balance) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Balance) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no balances provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(balanceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	balanceUpsertCacheMut.RLock()
	cache, cached := balanceUpsertCache[key]
	balanceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			balanceColumns,
			balanceColumnsWithDefault,
			balanceColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			balanceColumns,
			balancePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert balances, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(balancePrimaryKeyColumns))
			copy(conflict, balancePrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"balances\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(balanceType, balanceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(balanceType, balanceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert balances")
	}

	if !cached {
		balanceUpsertCacheMut.Lock()
		balanceUpsertCache[key] = cache
		balanceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Balance record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Balance) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Balance record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Balance) DeleteG() error {
	if o == nil {
		return errors.New("models: no Balance provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Balance record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Balance) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Balance record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Balance) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Balance provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), balancePrimaryKeyMapping)
	sql := "DELETE FROM \"balances\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from balances")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q balanceQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q balanceQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no balanceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from balances")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o BalanceSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o BalanceSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Balance slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o BalanceSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BalanceSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Balance slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(balanceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), balancePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"balances\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, balancePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from balance slice")
	}

	if len(balanceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Balance) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Balance) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Balance) ReloadG() error {
	if o == nil {
		return errors.New("models: no Balance provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Balance) Reload(exec boil.Executor) error {
	ret, err := FindBalance(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BalanceSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *BalanceSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BalanceSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty BalanceSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BalanceSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	balances := BalanceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), balancePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"balances\".* FROM \"balances\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, balancePrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&balances)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in BalanceSlice")
	}

	*o = balances

	return nil
}

// BalanceExists checks if the Balance row exists.
func BalanceExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"balances\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if balances exists")
	}

	return exists, nil
}

// BalanceExistsG checks if the Balance row exists.
func BalanceExistsG(id int) (bool, error) {
	return BalanceExists(boil.GetDB(), id)
}

// BalanceExistsGP checks if the Balance row exists. Panics on error.
func BalanceExistsGP(id int) bool {
	e, err := BalanceExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// BalanceExistsP checks if the Balance row exists. Panics on error.
func BalanceExistsP(exec boil.Executor, id int) bool {
	e, err := BalanceExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
