// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Snapshot is an object representing the database table.
type Snapshot struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *snapshotR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L snapshotL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SnapshotColumns = struct {
	ID        string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// snapshotR is where relationships are stored.
type snapshotR struct {
	Balances BalanceSlice
}

// snapshotL is where Load methods for each relationship are stored.
type snapshotL struct{}

var (
	snapshotColumns               = []string{"id", "created_at", "updated_at"}
	snapshotColumnsWithoutDefault = []string{"created_at", "updated_at"}
	snapshotColumnsWithDefault    = []string{"id"}
	snapshotPrimaryKeyColumns     = []string{"id"}
)

type (
	// SnapshotSlice is an alias for a slice of pointers to Snapshot.
	// This should generally be used opposed to []Snapshot.
	SnapshotSlice []*Snapshot
	// SnapshotHook is the signature for custom Snapshot hook methods
	SnapshotHook func(boil.Executor, *Snapshot) error

	snapshotQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	snapshotType                 = reflect.TypeOf(&Snapshot{})
	snapshotMapping              = queries.MakeStructMapping(snapshotType)
	snapshotPrimaryKeyMapping, _ = queries.BindMapping(snapshotType, snapshotMapping, snapshotPrimaryKeyColumns)
	snapshotInsertCacheMut       sync.RWMutex
	snapshotInsertCache          = make(map[string]insertCache)
	snapshotUpdateCacheMut       sync.RWMutex
	snapshotUpdateCache          = make(map[string]updateCache)
	snapshotUpsertCacheMut       sync.RWMutex
	snapshotUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var snapshotBeforeInsertHooks []SnapshotHook
var snapshotBeforeUpdateHooks []SnapshotHook
var snapshotBeforeDeleteHooks []SnapshotHook
var snapshotBeforeUpsertHooks []SnapshotHook

var snapshotAfterInsertHooks []SnapshotHook
var snapshotAfterSelectHooks []SnapshotHook
var snapshotAfterUpdateHooks []SnapshotHook
var snapshotAfterDeleteHooks []SnapshotHook
var snapshotAfterUpsertHooks []SnapshotHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Snapshot) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Snapshot) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Snapshot) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Snapshot) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Snapshot) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Snapshot) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Snapshot) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Snapshot) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Snapshot) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range snapshotAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSnapshotHook registers your hook function for all future operations.
func AddSnapshotHook(hookPoint boil.HookPoint, snapshotHook SnapshotHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		snapshotBeforeInsertHooks = append(snapshotBeforeInsertHooks, snapshotHook)
	case boil.BeforeUpdateHook:
		snapshotBeforeUpdateHooks = append(snapshotBeforeUpdateHooks, snapshotHook)
	case boil.BeforeDeleteHook:
		snapshotBeforeDeleteHooks = append(snapshotBeforeDeleteHooks, snapshotHook)
	case boil.BeforeUpsertHook:
		snapshotBeforeUpsertHooks = append(snapshotBeforeUpsertHooks, snapshotHook)
	case boil.AfterInsertHook:
		snapshotAfterInsertHooks = append(snapshotAfterInsertHooks, snapshotHook)
	case boil.AfterSelectHook:
		snapshotAfterSelectHooks = append(snapshotAfterSelectHooks, snapshotHook)
	case boil.AfterUpdateHook:
		snapshotAfterUpdateHooks = append(snapshotAfterUpdateHooks, snapshotHook)
	case boil.AfterDeleteHook:
		snapshotAfterDeleteHooks = append(snapshotAfterDeleteHooks, snapshotHook)
	case boil.AfterUpsertHook:
		snapshotAfterUpsertHooks = append(snapshotAfterUpsertHooks, snapshotHook)
	}
}

// OneP returns a single snapshot record from the query, and panics on error.
func (q snapshotQuery) OneP() *Snapshot {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single snapshot record from the query.
func (q snapshotQuery) One() (*Snapshot, error) {
	o := &Snapshot{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for snapshots")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Snapshot records from the query, and panics on error.
func (q snapshotQuery) AllP() SnapshotSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Snapshot records from the query.
func (q snapshotQuery) All() (SnapshotSlice, error) {
	var o []*Snapshot

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Snapshot slice")
	}

	if len(snapshotAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Snapshot records in the query, and panics on error.
func (q snapshotQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Snapshot records in the query.
func (q snapshotQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count snapshots rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q snapshotQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q snapshotQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if snapshots exists")
	}

	return count > 0, nil
}

// BalancesG retrieves all the balance's balances.
func (o *Snapshot) BalancesG(mods ...qm.QueryMod) balanceQuery {
	return o.Balances(boil.GetDB(), mods...)
}

// Balances retrieves all the balance's balances with an executor.
func (o *Snapshot) Balances(exec boil.Executor, mods ...qm.QueryMod) balanceQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"balances\".\"snapshot_id\"=?", o.ID),
	)

	query := Balances(exec, queryMods...)
	queries.SetFrom(query.Query, "\"balances\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"balances\".*"})
	}

	return query
}

// LoadBalances allows an eager lookup of values, cached into the
// loaded structs of the objects.
func (snapshotL) LoadBalances(e boil.Executor, singular bool, maybeSnapshot interface{}) error {
	var slice []*Snapshot
	var object *Snapshot

	count := 1
	if singular {
		object = maybeSnapshot.(*Snapshot)
	} else {
		slice = *maybeSnapshot.(*[]*Snapshot)
		count = len(slice)
	}

	args := make([]interface{}, count)
	if singular {
		if object.R == nil {
			object.R = &snapshotR{}
		}
		args[0] = object.ID
	} else {
		for i, obj := range slice {
			if obj.R == nil {
				obj.R = &snapshotR{}
			}
			args[i] = obj.ID
		}
	}

	query := fmt.Sprintf(
		"select * from \"balances\" where \"snapshot_id\" in (%s)",
		strmangle.Placeholders(dialect.IndexPlaceholders, count, 1, 1),
	)
	if boil.DebugMode {
		fmt.Fprintf(boil.DebugWriter, "%s\n%v\n", query, args)
	}

	results, err := e.Query(query, args...)
	if err != nil {
		return errors.Wrap(err, "failed to eager load balances")
	}
	defer results.Close()

	var resultSlice []*Balance
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice balances")
	}

	if len(balanceAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Balances = resultSlice
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SnapshotID {
				local.R.Balances = append(local.R.Balances, foreign)
				break
			}
		}
	}

	return nil
}

// AddBalancesG adds the given related objects to the existing relationships
// of the snapshot, optionally inserting them as new records.
// Appends related to o.R.Balances.
// Sets related.R.Snapshot appropriately.
// Uses the global database handle.
func (o *Snapshot) AddBalancesG(insert bool, related ...*Balance) error {
	return o.AddBalances(boil.GetDB(), insert, related...)
}

// AddBalancesP adds the given related objects to the existing relationships
// of the snapshot, optionally inserting them as new records.
// Appends related to o.R.Balances.
// Sets related.R.Snapshot appropriately.
// Panics on error.
func (o *Snapshot) AddBalancesP(exec boil.Executor, insert bool, related ...*Balance) {
	if err := o.AddBalances(exec, insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddBalancesGP adds the given related objects to the existing relationships
// of the snapshot, optionally inserting them as new records.
// Appends related to o.R.Balances.
// Sets related.R.Snapshot appropriately.
// Uses the global database handle and panics on error.
func (o *Snapshot) AddBalancesGP(insert bool, related ...*Balance) {
	if err := o.AddBalances(boil.GetDB(), insert, related...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// AddBalances adds the given related objects to the existing relationships
// of the snapshot, optionally inserting them as new records.
// Appends related to o.R.Balances.
// Sets related.R.Snapshot appropriately.
func (o *Snapshot) AddBalances(exec boil.Executor, insert bool, related ...*Balance) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SnapshotID = o.ID
			if err = rel.Insert(exec); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"balances\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"snapshot_id"}),
				strmangle.WhereClause("\"", "\"", 2, balancePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.DebugMode {
				fmt.Fprintln(boil.DebugWriter, updateQuery)
				fmt.Fprintln(boil.DebugWriter, values)
			}

			if _, err = exec.Exec(updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SnapshotID = o.ID
		}
	}

	if o.R == nil {
		o.R = &snapshotR{
			Balances: related,
		}
	} else {
		o.R.Balances = append(o.R.Balances, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &balanceR{
				Snapshot: o,
			}
		} else {
			rel.R.Snapshot = o
		}
	}
	return nil
}

// SnapshotsG retrieves all records.
func SnapshotsG(mods ...qm.QueryMod) snapshotQuery {
	return Snapshots(boil.GetDB(), mods...)
}

// Snapshots retrieves all the records using an executor.
func Snapshots(exec boil.Executor, mods ...qm.QueryMod) snapshotQuery {
	mods = append(mods, qm.From("\"snapshots\""))
	return snapshotQuery{NewQuery(exec, mods...)}
}

// FindSnapshotG retrieves a single record by ID.
func FindSnapshotG(id int, selectCols ...string) (*Snapshot, error) {
	return FindSnapshot(boil.GetDB(), id, selectCols...)
}

// FindSnapshotGP retrieves a single record by ID, and panics on error.
func FindSnapshotGP(id int, selectCols ...string) *Snapshot {
	retobj, err := FindSnapshot(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindSnapshot retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSnapshot(exec boil.Executor, id int, selectCols ...string) (*Snapshot, error) {
	snapshotObj := &Snapshot{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"snapshots\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(snapshotObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from snapshots")
	}

	return snapshotObj, nil
}

// FindSnapshotP retrieves a single record by ID with an executor, and panics on error.
func FindSnapshotP(exec boil.Executor, id int, selectCols ...string) *Snapshot {
	retobj, err := FindSnapshot(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Snapshot) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Snapshot) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Snapshot) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Snapshot) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no snapshots provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(snapshotColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	snapshotInsertCacheMut.RLock()
	cache, cached := snapshotInsertCache[key]
	snapshotInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			snapshotColumns,
			snapshotColumnsWithDefault,
			snapshotColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(snapshotType, snapshotMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(snapshotType, snapshotMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"snapshots\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"snapshots\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into snapshots")
	}

	if !cached {
		snapshotInsertCacheMut.Lock()
		snapshotInsertCache[key] = cache
		snapshotInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Snapshot record. See Update for
// whitelist behavior description.
func (o *Snapshot) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Snapshot record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Snapshot) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Snapshot, and panics on error.
// See Update for whitelist behavior description.
func (o *Snapshot) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Snapshot.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Snapshot) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	snapshotUpdateCacheMut.RLock()
	cache, cached := snapshotUpdateCache[key]
	snapshotUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			snapshotColumns,
			snapshotPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update snapshots, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"snapshots\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, snapshotPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(snapshotType, snapshotMapping, append(wl, snapshotPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update snapshots row")
	}

	if !cached {
		snapshotUpdateCacheMut.Lock()
		snapshotUpdateCache[key] = cache
		snapshotUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q snapshotQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q snapshotQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for snapshots")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o SnapshotSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o SnapshotSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o SnapshotSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SnapshotSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), snapshotPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"snapshots\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, snapshotPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in snapshot slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Snapshot) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Snapshot) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Snapshot) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Snapshot) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no snapshots provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(snapshotColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	snapshotUpsertCacheMut.RLock()
	cache, cached := snapshotUpsertCache[key]
	snapshotUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			snapshotColumns,
			snapshotColumnsWithDefault,
			snapshotColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			snapshotColumns,
			snapshotPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert snapshots, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(snapshotPrimaryKeyColumns))
			copy(conflict, snapshotPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"snapshots\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(snapshotType, snapshotMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(snapshotType, snapshotMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert snapshots")
	}

	if !cached {
		snapshotUpsertCacheMut.Lock()
		snapshotUpsertCache[key] = cache
		snapshotUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Snapshot record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Snapshot) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Snapshot record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Snapshot) DeleteG() error {
	if o == nil {
		return errors.New("models: no Snapshot provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Snapshot record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Snapshot) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Snapshot record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Snapshot) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Snapshot provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), snapshotPrimaryKeyMapping)
	sql := "DELETE FROM \"snapshots\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from snapshots")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q snapshotQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q snapshotQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no snapshotQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from snapshots")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o SnapshotSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o SnapshotSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Snapshot slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o SnapshotSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SnapshotSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Snapshot slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(snapshotBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), snapshotPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"snapshots\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, snapshotPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from snapshot slice")
	}

	if len(snapshotAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Snapshot) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Snapshot) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Snapshot) ReloadG() error {
	if o == nil {
		return errors.New("models: no Snapshot provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Snapshot) Reload(exec boil.Executor) error {
	ret, err := FindSnapshot(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *SnapshotSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *SnapshotSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SnapshotSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty SnapshotSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SnapshotSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	snapshots := SnapshotSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), snapshotPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"snapshots\".* FROM \"snapshots\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, snapshotPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&snapshots)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SnapshotSlice")
	}

	*o = snapshots

	return nil
}

// SnapshotExists checks if the Snapshot row exists.
func SnapshotExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"snapshots\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if snapshots exists")
	}

	return exists, nil
}

// SnapshotExistsG checks if the Snapshot row exists.
func SnapshotExistsG(id int) (bool, error) {
	return SnapshotExists(boil.GetDB(), id)
}

// SnapshotExistsGP checks if the Snapshot row exists. Panics on error.
func SnapshotExistsGP(id int) bool {
	e, err := SnapshotExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// SnapshotExistsP checks if the Snapshot row exists. Panics on error.
func SnapshotExistsP(exec boil.Executor, id int) bool {
	e, err := SnapshotExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
